// ==UserScript==
// @name          AddTags
// @namespace     http://github.com/dandavison/
// @description   Add buttons to wrap text with HTML tags
// @include       http://*/*
// @include       https://*/*
// ==/UserScript==

// Generated by CoffeeScript 1.3.1
(function() {
  var template, wrap;

  template = '<div class="addtags-button-container">\n    <button class="addtags-b"> bold </button>\n    <button class="addtags-i"> italic </button>\n    <button class="addtags-a"> link </button>\n    <button class="addtags-blockquote"> blockquote </button>\n    <button class="addtags-p"> paragraph </button>\n</div>';

  wrap = function(textarea, tag, extra) {
    var after, before, selection, wrapped;
    if (extra == null) {
      extra = '';
    }
    selection = textarea.value.substring(textarea.selectionStart, textarea.selectionEnd);
    wrapped = "<" + (tag + extra) + ">" + selection + "</" + tag + ">";
    before = textarea.value.substring(0, textarea.selectionStart);
    after = textarea.value.substring(textarea.selectionEnd, textarea.value.length);
    return textarea.value = before + wrapped + after;
  };

  $(function() {
    var $template, extra, tag, textarea, _i, _len, _ref, _results;
    _ref = $('textarea');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      textarea = _ref[_i];
      $template = $(template);
      $(textarea).before($template);
      _results.push((function() {
        var _j, _len1, _ref1, _results1;
        _ref1 = ['b', 'i', 'a', 'blockquote', 'p'];
        _results1 = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          tag = _ref1[_j];
          extra = tag === 'a' ? ' href=""' : '';
          _results1.push((function(textarea, $template, tag, extra) {
            return $template.find("button.addtags-" + tag).click(function() {
              wrap(textarea, tag, extra);
              return false;
            });
          })(textarea, $template, tag, extra));
        }
        return _results1;
      })());
    }
    return _results;
  });

}).call(this);
